/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AudienciasRouteImport } from './routes/audiencias'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as ProcessosContratosRouteImport } from './routes/processos-contratos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SugestoesRouteImport } from './routes/sugestoes'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminPainelExecutivoRouteImport } from './routes/admin.painel-executivo'
import { Route as CadastrosClientesRouteImport } from './routes/cadastros.clientes'
import { Route as CadastrosProfissionaisRouteImport } from './routes/cadastros.profissionais'
import { Route as FinancasDespesasRouteImport } from './routes/financas.despesas'
import { Route as FinancasRecebimentosRouteImport } from './routes/financas.recebimentos'
import { Route as ModelosIdRouteImport } from './routes/modelos.$id'
import { Route as ProcessosIdRouteImport } from './routes/processos.$id'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminAlertasRouteImport } from './routes/super-admin.alertas'
import { Route as SuperAdminConfiguracoesRouteImport } from './routes/super-admin.configuracoes'
import { Route as SuperAdminEmpresasRouteImport } from './routes/super-admin.empresas'
import { Route as SuperAdminEstatisticasRouteImport } from './routes/super-admin.estatisticas'
import { Route as SuperAdminFinanceiroRouteImport } from './routes/super-admin.financeiro'
import { Route as SuperAdminLicencasRouteImport } from './routes/super-admin.licencas'
import { Route as AdminEmpresasCompanyIdRouteImport } from './routes/admin.empresas.$companyId'
import { Route as SuperAdminEmpresasCompanyIdRouteImport } from './routes/super-admin.empresas.$companyId'
import { Route as SuperAdminEmpresasNovaRouteImport } from './routes/super-admin.empresas.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienciasRoute = AudienciasRouteImport.update({
  id: '/audiencias',
  path: '/audiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosContratosRoute = ProcessosContratosRouteImport.update({
  id: '/processos-contratos',
  path: '/processos-contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SugestoesRoute = SugestoesRouteImport.update({
  id: '/sugestoes',
  path: '/sugestoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/admin/empresas',
  path: '/admin/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPainelExecutivoRoute = AdminPainelExecutivoRouteImport.update({
  id: '/admin/painel-executivo',
  path: '/admin/painel-executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosClientesRoute = CadastrosClientesRouteImport.update({
  id: '/cadastros/clientes',
  path: '/cadastros/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosProfissionaisRoute = CadastrosProfissionaisRouteImport.update({
  id: '/cadastros/profissionais',
  path: '/cadastros/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasDespesasRoute = FinancasDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => FinancasRoute,
} as any)
const FinancasRecebimentosRoute = FinancasRecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => FinancasRoute,
} as any)
const ModelosIdRoute = ModelosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ModelosRoute,
} as any)
const ProcessosIdRoute = ProcessosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProcessosRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAlertasRoute = SuperAdminAlertasRouteImport.update({
  id: '/super-admin/alertas',
  path: '/super-admin/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminConfiguracoesRoute = SuperAdminConfiguracoesRouteImport.update({
  id: '/super-admin/configuracoes',
  path: '/super-admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminEmpresasRoute = SuperAdminEmpresasRouteImport.update({
  id: '/super-admin/empresas',
  path: '/super-admin/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminEstatisticasRoute = SuperAdminEstatisticasRouteImport.update({
  id: '/super-admin/estatisticas',
  path: '/super-admin/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminFinanceiroRoute = SuperAdminFinanceiroRouteImport.update({
  id: '/super-admin/financeiro',
  path: '/super-admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLicencasRoute = SuperAdminLicencasRouteImport.update({
  id: '/super-admin/licencas',
  path: '/super-admin/licencas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasCompanyIdRoute = AdminEmpresasCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AdminEmpresasRoute,
} as any)
const SuperAdminEmpresasCompanyIdRoute =
  SuperAdminEmpresasCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => SuperAdminEmpresasRoute,
  } as any)
const SuperAdminEmpresasNovaRoute = SuperAdminEmpresasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => SuperAdminEmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/audiencias': typeof AudienciasRoute
  '/automacao': typeof AutomacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/empresa': typeof EmpresaRoute
  '/financas': typeof FinancasRouteWithChildren
  '/imoveis': typeof ImoveisRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRouteWithChildren
  '/processos': typeof ProcessosRouteWithChildren
  '/processos-contratos': typeof ProcessosContratosRoute
  '/signup': typeof SignupRoute
  '/sobre': typeof SobreRoute
  '/sugestoes': typeof SugestoesRoute
  '/suspended': typeof SuspendedRoute
  '/tarefas': typeof TarefasRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/admin/painel-executivo': typeof AdminPainelExecutivoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/profissionais': typeof CadastrosProfissionaisRoute
  '/financas/despesas': typeof FinancasDespesasRoute
  '/financas/recebimentos': typeof FinancasRecebimentosRoute
  '/modelos/$id': typeof ModelosIdRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/super-admin/alertas': typeof SuperAdminAlertasRoute
  '/super-admin/configuracoes': typeof SuperAdminConfiguracoesRoute
  '/super-admin/empresas': typeof SuperAdminEmpresasRouteWithChildren
  '/super-admin/estatisticas': typeof SuperAdminEstatisticasRoute
  '/super-admin/financeiro': typeof SuperAdminFinanceiroRoute
  '/super-admin/licencas': typeof SuperAdminLicencasRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/empresas/$companyId': typeof AdminEmpresasCompanyIdRoute
  '/super-admin/empresas/$companyId': typeof SuperAdminEmpresasCompanyIdRoute
  '/super-admin/empresas/nova': typeof SuperAdminEmpresasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/audiencias': typeof AudienciasRoute
  '/automacao': typeof AutomacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/empresa': typeof EmpresaRoute
  '/financas': typeof FinancasRouteWithChildren
  '/imoveis': typeof ImoveisRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRouteWithChildren
  '/processos': typeof ProcessosRouteWithChildren
  '/processos-contratos': typeof ProcessosContratosRoute
  '/signup': typeof SignupRoute
  '/sobre': typeof SobreRoute
  '/sugestoes': typeof SugestoesRoute
  '/suspended': typeof SuspendedRoute
  '/tarefas': typeof TarefasRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/admin/painel-executivo': typeof AdminPainelExecutivoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/profissionais': typeof CadastrosProfissionaisRoute
  '/financas/despesas': typeof FinancasDespesasRoute
  '/financas/recebimentos': typeof FinancasRecebimentosRoute
  '/modelos/$id': typeof ModelosIdRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/super-admin/alertas': typeof SuperAdminAlertasRoute
  '/super-admin/configuracoes': typeof SuperAdminConfiguracoesRoute
  '/super-admin/empresas': typeof SuperAdminEmpresasRouteWithChildren
  '/super-admin/estatisticas': typeof SuperAdminEstatisticasRoute
  '/super-admin/financeiro': typeof SuperAdminFinanceiroRoute
  '/super-admin/licencas': typeof SuperAdminLicencasRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/admin/empresas/$companyId': typeof AdminEmpresasCompanyIdRoute
  '/super-admin/empresas/$companyId': typeof SuperAdminEmpresasCompanyIdRoute
  '/super-admin/empresas/nova': typeof SuperAdminEmpresasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/audiencias': typeof AudienciasRoute
  '/automacao': typeof AutomacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/empresa': typeof EmpresaRoute
  '/financas': typeof FinancasRouteWithChildren
  '/imoveis': typeof ImoveisRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRouteWithChildren
  '/processos': typeof ProcessosRouteWithChildren
  '/processos-contratos': typeof ProcessosContratosRoute
  '/signup': typeof SignupRoute
  '/sobre': typeof SobreRoute
  '/sugestoes': typeof SugestoesRoute
  '/suspended': typeof SuspendedRoute
  '/tarefas': typeof TarefasRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/admin/painel-executivo': typeof AdminPainelExecutivoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/profissionais': typeof CadastrosProfissionaisRoute
  '/financas/despesas': typeof FinancasDespesasRoute
  '/financas/recebimentos': typeof FinancasRecebimentosRoute
  '/modelos/$id': typeof ModelosIdRoute
  '/processos/$id': typeof ProcessosIdRoute
  '/super-admin/alertas': typeof SuperAdminAlertasRoute
  '/super-admin/configuracoes': typeof SuperAdminConfiguracoesRoute
  '/super-admin/empresas': typeof SuperAdminEmpresasRouteWithChildren
  '/super-admin/estatisticas': typeof SuperAdminEstatisticasRoute
  '/super-admin/financeiro': typeof SuperAdminFinanceiroRoute
  '/super-admin/licencas': typeof SuperAdminLicencasRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/empresas/$companyId': typeof AdminEmpresasCompanyIdRoute
  '/super-admin/empresas/$companyId': typeof SuperAdminEmpresasCompanyIdRoute
  '/super-admin/empresas/nova': typeof SuperAdminEmpresasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/audiencias'
    | '/automacao'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresa'
    | '/financas'
    | '/imoveis'
    | '/leads'
    | '/login'
    | '/modelos'
    | '/processos'
    | '/processos-contratos'
    | '/signup'
    | '/sobre'
    | '/sugestoes'
    | '/suspended'
    | '/tarefas'
    | '/unauthorized'
    | '/admin/empresas'
    | '/admin/painel-executivo'
    | '/cadastros/clientes'
    | '/cadastros/profissionais'
    | '/financas/despesas'
    | '/financas/recebimentos'
    | '/modelos/$id'
    | '/processos/$id'
    | '/super-admin/alertas'
    | '/super-admin/configuracoes'
    | '/super-admin/empresas'
    | '/super-admin/estatisticas'
    | '/super-admin/financeiro'
    | '/super-admin/licencas'
    | '/super-admin/'
    | '/admin/empresas/$companyId'
    | '/super-admin/empresas/$companyId'
    | '/super-admin/empresas/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/audiencias'
    | '/automacao'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresa'
    | '/financas'
    | '/imoveis'
    | '/leads'
    | '/login'
    | '/modelos'
    | '/processos'
    | '/processos-contratos'
    | '/signup'
    | '/sobre'
    | '/sugestoes'
    | '/suspended'
    | '/tarefas'
    | '/unauthorized'
    | '/admin/empresas'
    | '/admin/painel-executivo'
    | '/cadastros/clientes'
    | '/cadastros/profissionais'
    | '/financas/despesas'
    | '/financas/recebimentos'
    | '/modelos/$id'
    | '/processos/$id'
    | '/super-admin/alertas'
    | '/super-admin/configuracoes'
    | '/super-admin/empresas'
    | '/super-admin/estatisticas'
    | '/super-admin/financeiro'
    | '/super-admin/licencas'
    | '/super-admin'
    | '/admin/empresas/$companyId'
    | '/super-admin/empresas/$companyId'
    | '/super-admin/empresas/nova'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/audiencias'
    | '/automacao'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresa'
    | '/financas'
    | '/imoveis'
    | '/leads'
    | '/login'
    | '/modelos'
    | '/processos'
    | '/processos-contratos'
    | '/signup'
    | '/sobre'
    | '/sugestoes'
    | '/suspended'
    | '/tarefas'
    | '/unauthorized'
    | '/admin/empresas'
    | '/admin/painel-executivo'
    | '/cadastros/clientes'
    | '/cadastros/profissionais'
    | '/financas/despesas'
    | '/financas/recebimentos'
    | '/modelos/$id'
    | '/processos/$id'
    | '/super-admin/alertas'
    | '/super-admin/configuracoes'
    | '/super-admin/empresas'
    | '/super-admin/estatisticas'
    | '/super-admin/financeiro'
    | '/super-admin/licencas'
    | '/super-admin/'
    | '/admin/empresas/$companyId'
    | '/super-admin/empresas/$companyId'
    | '/super-admin/empresas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AudienciasRoute: typeof AudienciasRoute
  AutomacaoRoute: typeof AutomacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  DashboardRoute: typeof DashboardRoute
  EmpresaRoute: typeof EmpresaRoute
  FinancasRoute: typeof FinancasRouteWithChildren
  ImoveisRoute: typeof ImoveisRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  ModelosRoute: typeof ModelosRouteWithChildren
  ProcessosRoute: typeof ProcessosRouteWithChildren
  ProcessosContratosRoute: typeof ProcessosContratosRoute
  SignupRoute: typeof SignupRoute
  SobreRoute: typeof SobreRoute
  SugestoesRoute: typeof SugestoesRoute
  SuspendedRoute: typeof SuspendedRoute
  TarefasRoute: typeof TarefasRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminEmpresasRoute: typeof AdminEmpresasRouteWithChildren
  AdminPainelExecutivoRoute: typeof AdminPainelExecutivoRoute
  CadastrosClientesRoute: typeof CadastrosClientesRoute
  CadastrosProfissionaisRoute: typeof CadastrosProfissionaisRoute
  SuperAdminAlertasRoute: typeof SuperAdminAlertasRoute
  SuperAdminConfiguracoesRoute: typeof SuperAdminConfiguracoesRoute
  SuperAdminEmpresasRoute: typeof SuperAdminEmpresasRouteWithChildren
  SuperAdminEstatisticasRoute: typeof SuperAdminEstatisticasRoute
  SuperAdminFinanceiroRoute: typeof SuperAdminFinanceiroRoute
  SuperAdminLicencasRoute: typeof SuperAdminLicencasRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiencias': {
      id: '/audiencias'
      path: '/audiencias'
      fullPath: '/audiencias'
      preLoaderRoute: typeof AudienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos-contratos': {
      id: '/processos-contratos'
      path: '/processos-contratos'
      fullPath: '/processos-contratos'
      preLoaderRoute: typeof ProcessosContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sugestoes': {
      id: '/sugestoes'
      path: '/sugestoes'
      fullPath: '/sugestoes'
      preLoaderRoute: typeof SugestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/admin/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/painel-executivo': {
      id: '/admin/painel-executivo'
      path: '/admin/painel-executivo'
      fullPath: '/admin/painel-executivo'
      preLoaderRoute: typeof AdminPainelExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/clientes': {
      id: '/cadastros/clientes'
      path: '/cadastros/clientes'
      fullPath: '/cadastros/clientes'
      preLoaderRoute: typeof CadastrosClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/profissionais': {
      id: '/cadastros/profissionais'
      path: '/cadastros/profissionais'
      fullPath: '/cadastros/profissionais'
      preLoaderRoute: typeof CadastrosProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas/despesas': {
      id: '/financas/despesas'
      path: '/despesas'
      fullPath: '/financas/despesas'
      preLoaderRoute: typeof FinancasDespesasRouteImport
      parentRoute: typeof FinancasRoute
    }
    '/financas/recebimentos': {
      id: '/financas/recebimentos'
      path: '/recebimentos'
      fullPath: '/financas/recebimentos'
      preLoaderRoute: typeof FinancasRecebimentosRouteImport
      parentRoute: typeof FinancasRoute
    }
    '/modelos/$id': {
      id: '/modelos/$id'
      path: '/$id'
      fullPath: '/modelos/$id'
      preLoaderRoute: typeof ModelosIdRouteImport
      parentRoute: typeof ModelosRoute
    }
    '/processos/$id': {
      id: '/processos/$id'
      path: '/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof ProcessosIdRouteImport
      parentRoute: typeof ProcessosRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/alertas': {
      id: '/super-admin/alertas'
      path: '/super-admin/alertas'
      fullPath: '/super-admin/alertas'
      preLoaderRoute: typeof SuperAdminAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/configuracoes': {
      id: '/super-admin/configuracoes'
      path: '/super-admin/configuracoes'
      fullPath: '/super-admin/configuracoes'
      preLoaderRoute: typeof SuperAdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/empresas': {
      id: '/super-admin/empresas'
      path: '/super-admin/empresas'
      fullPath: '/super-admin/empresas'
      preLoaderRoute: typeof SuperAdminEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/estatisticas': {
      id: '/super-admin/estatisticas'
      path: '/super-admin/estatisticas'
      fullPath: '/super-admin/estatisticas'
      preLoaderRoute: typeof SuperAdminEstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/financeiro': {
      id: '/super-admin/financeiro'
      path: '/super-admin/financeiro'
      fullPath: '/super-admin/financeiro'
      preLoaderRoute: typeof SuperAdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/licencas': {
      id: '/super-admin/licencas'
      path: '/super-admin/licencas'
      fullPath: '/super-admin/licencas'
      preLoaderRoute: typeof SuperAdminLicencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas/$companyId': {
      id: '/admin/empresas/$companyId'
      path: '/$companyId'
      fullPath: '/admin/empresas/$companyId'
      preLoaderRoute: typeof AdminEmpresasCompanyIdRouteImport
      parentRoute: typeof AdminEmpresasRoute
    }
    '/super-admin/empresas/$companyId': {
      id: '/super-admin/empresas/$companyId'
      path: '/$companyId'
      fullPath: '/super-admin/empresas/$companyId'
      preLoaderRoute: typeof SuperAdminEmpresasCompanyIdRouteImport
      parentRoute: typeof SuperAdminEmpresasRoute
    }
    '/super-admin/empresas/nova': {
      id: '/super-admin/empresas/nova'
      path: '/nova'
      fullPath: '/super-admin/empresas/nova'
      preLoaderRoute: typeof SuperAdminEmpresasNovaRouteImport
      parentRoute: typeof SuperAdminEmpresasRoute
    }
  }
}

interface FinancasRouteChildren {
  FinancasDespesasRoute: typeof FinancasDespesasRoute
  FinancasRecebimentosRoute: typeof FinancasRecebimentosRoute
}

const FinancasRouteChildren: FinancasRouteChildren = {
  FinancasDespesasRoute: FinancasDespesasRoute,
  FinancasRecebimentosRoute: FinancasRecebimentosRoute,
}

const FinancasRouteWithChildren = FinancasRoute._addFileChildren(
  FinancasRouteChildren,
)

interface ModelosRouteChildren {
  ModelosIdRoute: typeof ModelosIdRoute
}

const ModelosRouteChildren: ModelosRouteChildren = {
  ModelosIdRoute: ModelosIdRoute,
}

const ModelosRouteWithChildren =
  ModelosRoute._addFileChildren(ModelosRouteChildren)

interface ProcessosRouteChildren {
  ProcessosIdRoute: typeof ProcessosIdRoute
}

const ProcessosRouteChildren: ProcessosRouteChildren = {
  ProcessosIdRoute: ProcessosIdRoute,
}

const ProcessosRouteWithChildren = ProcessosRoute._addFileChildren(
  ProcessosRouteChildren,
)

interface AdminEmpresasRouteChildren {
  AdminEmpresasCompanyIdRoute: typeof AdminEmpresasCompanyIdRoute
}

const AdminEmpresasRouteChildren: AdminEmpresasRouteChildren = {
  AdminEmpresasCompanyIdRoute: AdminEmpresasCompanyIdRoute,
}

const AdminEmpresasRouteWithChildren = AdminEmpresasRoute._addFileChildren(
  AdminEmpresasRouteChildren,
)

interface SuperAdminEmpresasRouteChildren {
  SuperAdminEmpresasCompanyIdRoute: typeof SuperAdminEmpresasCompanyIdRoute
  SuperAdminEmpresasNovaRoute: typeof SuperAdminEmpresasNovaRoute
}

const SuperAdminEmpresasRouteChildren: SuperAdminEmpresasRouteChildren = {
  SuperAdminEmpresasCompanyIdRoute: SuperAdminEmpresasCompanyIdRoute,
  SuperAdminEmpresasNovaRoute: SuperAdminEmpresasNovaRoute,
}

const SuperAdminEmpresasRouteWithChildren =
  SuperAdminEmpresasRoute._addFileChildren(SuperAdminEmpresasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AudienciasRoute: AudienciasRoute,
  AutomacaoRoute: AutomacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  DashboardRoute: DashboardRoute,
  EmpresaRoute: EmpresaRoute,
  FinancasRoute: FinancasRouteWithChildren,
  ImoveisRoute: ImoveisRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  ModelosRoute: ModelosRouteWithChildren,
  ProcessosRoute: ProcessosRouteWithChildren,
  ProcessosContratosRoute: ProcessosContratosRoute,
  SignupRoute: SignupRoute,
  SobreRoute: SobreRoute,
  SugestoesRoute: SugestoesRoute,
  SuspendedRoute: SuspendedRoute,
  TarefasRoute: TarefasRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminEmpresasRoute: AdminEmpresasRouteWithChildren,
  AdminPainelExecutivoRoute: AdminPainelExecutivoRoute,
  CadastrosClientesRoute: CadastrosClientesRoute,
  CadastrosProfissionaisRoute: CadastrosProfissionaisRoute,
  SuperAdminAlertasRoute: SuperAdminAlertasRoute,
  SuperAdminConfiguracoesRoute: SuperAdminConfiguracoesRoute,
  SuperAdminEmpresasRoute: SuperAdminEmpresasRouteWithChildren,
  SuperAdminEstatisticasRoute: SuperAdminEstatisticasRoute,
  SuperAdminFinanceiroRoute: SuperAdminFinanceiroRoute,
  SuperAdminLicencasRoute: SuperAdminLicencasRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
