// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data, error } = await supabase.auth.getSession();
    const hasSession = !!data.session;
    const userId = data.session?.user?.id;
    const token = data.session?.access_token;
    const tokenPreview = token ? `${token.slice(0, 8)}...${token.slice(-8)}` : "no-token";

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
